## 配置端口
server:
  port: 8081

spring:
  ## 配置数据库数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.102:3306/mydatabase
    username: myuser
    password: mypassword
  redis:
    # 地址
    host: 192.168.56.102
    # 端口
    port: 6379
    # 密码
    password:
    # 超时时间 5000毫秒
    timeout: 5000
    jedis:
      pool:
        # 连接池最小空闲连接
        min-idle: 0
        # 连接池的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负数表示没有限制）
        max-wait: -1
        # 连接池最大连接数（使用负数表示没有限制）
        max-active: 8


# MyBatis Plus 的配置
mybatis-plus:
  # mybatis 配置文件的路径
  # config-location: "classpath:mybatis/mybatis.config"
  # mapper 映射文件的路径，可以有多个
  mapper-locations:
    - "classpath*:mappers/**/*.xml"

